config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :events, :only => [:index, :new, :create, :show, :edit, :update]

  get '/moremoney', to: 'tickets#more_money'
  post '/ticket/markForDelete/:id', to: 'tickets#set_to_delete'

  get '/tickets/show_filtered/:from/:to', to: 'tickets#filter'

  resources :tickets
  root :to => "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	validates :artist, presence: true
	validates :price_low, presence: true
	validates :price_high, presence: true
	validates :event_date, presence: true
	validates :event_date, presence: true
	validates :sell_start_date, presence: true
	validate :event_date_not_from_past
	validates :price_high, numericality: true
    validates :price_low, numericality: true


    has_many :tickets

	def event_date_not_from_past
		if !event_date.nil?
		    if event_date< Date.today
		      errors.add('Event date ','cannot be from the past')
		    end
		end
 	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin, only: [:edit, :update]
	#before_action :check_logged_in, :only => [:new, :create]

  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
      if @event.save
        flash[:komunikat] = 'Ticket was successfully created.'
        redirect_to "/events/#{@event.id}", notice: 'Event was successfully created.'
      else
       	render :new
      end
  end

  def index
    @events = Event.all
  end

  def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.' 
      else
        format.html { render :edit }
      end
  end

  def edit
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:artist, :description,:price_low, :price_high, :event_date, :spots, :spots_sold, :min_age, :sell_start_date)
    end

    def is_admin
      redirect_to events_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if current_user.nil? || current_user.role != 'admin'
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form-container">
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist, 'Event name' %>
    <%= form.text_field :artist, id: :event_artist, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :price_low , 'Ticket price'%>
    <%= form.text_field :price_low, id: :event_price_low , class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.hidden_field :price_high, id: :event_price_high, :value => 0, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= form.hidden_field :spots_sold, id: :event_spots_sold, :value => 0 , class: 'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :event_date %>
    <%= form.text_field :event_date, id: :event_event_date , class: 'form-control' %>
  </div>
    <div class="field">
    <%= form.label :spots, "Spots available"%>
    <%= form.text_field :spots, id: :event_spots, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :min_age, "Minimum age to buy"%>
    <%= form.text_field :min_age, id: :event_min_age, class: 'form-control'  %>
  </div>
    <div class="field">
    <%= form.label :sell_start_date%>
    <%= form.text_field :sell_start_date, id: :event_sell_start_date, class: 'form-control'  %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1> All Events</h1>
<table class="table">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Event Date</th>
      <th>Sold</th>
      <th>Sell start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
        <tr>
          <td><%= event.artist %></td>
          <td><%= event.event_date %></td>
          <td><%= event.spots_sold %>/<%= event.spots %></td>
          <td><%= event.sell_start_date %></td>
          <td><%= link_to 'Show', event %></td>
          <% if event.event_date >= Date.today && current_user != nil && current_user.role == 'admin' %>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
<% if current_user != nil && current_user.role == 'admin'%>
<%= link_to 'Nowe ogłoszenie', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<p>
  <strong>Price:</strong>
  <% if @event.event_date == Date.today %>
    <%= @event.price_low*1.2 %>
  <% else %>
    <%= @event.price_low %>
  <% end %>
</p>
<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>
<p>
  <strong>Spots pool:</strong>
  <%= @event.spots %> 
</p>
<p>
  <strong>Spots sold:</strong>
  <%= @event.spots_sold %> 
</p>
<p>
  <strong>Minimum age:</strong>
  <%= @event.min_age %> 
</p>
<p>
  <strong>Can be bought since:</strong>
  <%= @event.sell_start_date %> 
</p>
<%= link_to 'All events', events_path %>
<% if current_user != nil && current_user.role == 'admin'%>
   | <%= link_to 'Edit', edit_event_path(@event) %> 
<% end %>

<% if @event.sell_start_date <= Date.today && !current_user.nil? && current_user.date_of_birth <= @event.min_age.year.ago %>
  <% if @event.event_date > Date.today%>
    <%= render './tickets/form', ticket: Ticket.new(:event_id => @event.id, :user_id => current_user.id, :price => @event.price_low, :name => "justEmpty", :email_address => current_user.email, :phone => current_user.phone)%>
  <% end %>
  <% if @event.event_date == Date.today %>
    <%= render './tickets/form', ticket: Ticket.new(:event_id => @event.id, :user_id => current_user.id, :price => @event.price_low*1.2, :name => "justEmpty", :email_address => current_user.email, :phone => current_user.phone)%>
  <% end %>
<% end %>

<br><br>

<% if current_user != nil %>
  <%= render './tickets/list_tickets', tickets: Ticket.where(event_id: @event.id)%>
<% end %>