config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :events, :only => [:index, :new, :create, :show, :edit, :update]

  get '/moremoney', to: 'tickets#more_money'
  post '/ticket/markForDelete/:id', to: 'tickets#set_to_delete'

  get '/tickets/show_filtered/:from/:to', to: 'tickets#filter'

  resources :tickets
  root :to => "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	validates :name, presence: true 
	validates :name, length: { :minimum => 6 }
	validates :email_address, presence: true
	validates_format_of :email_address ,:with => Devise::email_regexp
	validates :price, presence: true
	validates :price, numericality: true
	validates :amount, numericality: {only_integer: true, greater_than_or_equal_to: 1}
	validates :phone, presence: true
	validates :phone, length: {:minimum => 8}
	validate :not_too_young
	validate :not_too_many_tickets
	validate :has_money
	validate :can_be_bought
	validate :not_decreasing_amount


	belongs_to :event
	belongs_to :user

	def not_too_young
		userDate = User.where(id: user_id)[0]
		event = Event.where(id: event_id)[0]
		if userDate.nil?
			errors.add('User ',' did not put date of birth')
		end
		if(userDate.date_of_birth > event.min_age.year.ago)
			errors.add('User ','is to young for this show')
		end
	end

	def not_decreasing_amount
		ticket = Ticket.where(id: id)[0]
		if !ticket.nil?
			if ticket.amount > amount
				errors.add('Amount: ',' cannot decrease amount')
			end
		end
	end

	def are_spots_empty
		event = Event.where(id: event_id)[0]
		if event.nil?
			errors.add('Amount: ',' not enaugh tickets left')
		end
		if event.spots - event.spots_sold < amount
			errors.add('Amount: ',' not enough tickets left')
		end
	end

	def not_too_many_tickets
    	sum = amount
    	tickets = Ticket.where(user_id: user_id, event_id: event_id)
    	tickets.each {|x| 
    		if x.id != id
    			sum+=x.amount
    		end
    	}
    	if sum > 5
    		errors.add('Amount',': To many tickets bought. Max 5 for event')
    	end
    end

    def has_money
    	moneyNeeded = price*amount;
    	ticket = Ticket.find_by(id: id)
    	if !ticket.nil?
    		moneyNeeded -= ticket.price * ticket.amount
    	end
    	moneyAvailable = User.find(user_id).money
    	if moneyNeeded>moneyAvailable
    		errors.add('Price',': You do not have enough money.')
    	end
    end

    def can_be_bought
    	event = Event.find(event_id)
    	if(event.sell_start_date>Date.today || event.event_date < Date.today)
    		errors.add('Date', 'You cannot buy tickets for this event now')
    	end
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :set_to_delete]
  before_action :only_admin, only: [:destroy]
  # GET /tickets
  # GET /tickets.json
  def index
    if(current_user.role == 'admin')
      @tickets = Ticket.all
    else
      @tickets = current_user.tickets
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(user_id: current_user.id)
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    event = Event.find(@ticket.event_id)
    event.spots_sold += @ticket.amount
    user = User.find(@ticket.user_id)
    user.money -= @ticket.price*@ticket.amount
    respond_to do |format|
      if @ticket.save
        user.save
        event.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
    event = Event.find(@ticket.event_id)
    prevAmount = @ticket.amount
    user = User.find(@ticket.user_id)
      if @ticket.update(ticket_params)
        event.spots_sold -=prevAmount - @ticket.amount
        event.save
        user.money += (prevAmount - @ticket.amount) * @ticket.price
        user.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    event = Event.find(@ticket.event_id)
    event.spots_sold -= @ticket.amount
    user = User.find(@ticket.user_id)
    user.money += @ticket.price*@ticket.amount*return_percent_money(event.event_date)
    @ticket.destroy
    respond_to do |format|
      event.save
      user.save
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_to_delete
    ticket = Ticket.find(params[:id])
    ticket.to_delete = true
    ticket.save
    @tickets = current_user.tickets
    render :index, notice: 'Ticket was marked for cancelation'
  end

  def filter
    dateFrom = Date.parse(params[:form])
  end

  def more_money
    user = current_user
    current_user.money += 100
    current_user.save
    redirect_to '/' , notice: 'Money increased'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def goodAmount
      sum = ticket_params[:amount].to_i
      if sum > 5
        flash[:notice] = "You cannot buy more than 5 tickets for one event"
        render 
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:price, :email_address, :phone,:event_id, :user_id, :amount, :name,:from)
    end
    def correct_user
      if(current_user.role != 'admin')
        @ticket = current_user.tickets.find_by(id: params[:id])
        redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
      end
    end
    def only_admin
      if(current_user.role != 'admin')
        redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu"
      end
    end

    def return_percent_money (date)
      if(30.days.from_now < date)
        return 0.6
      elsif 15.days.from_now < date
        return 0.5
      elsif 7.days.from_now < date
        return 0.3
      elsif 3.days.from_now < date
        return 0.2
      else
        return 0.1
      end
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<div class="form-container">
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price, 'Price for ticket' %>
    <%= form.text_field :price, id: :ticket_price, :readonly => true, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :email_address, 'Contact email' %>
    <%= form.text_field :email_address, id: :ticket_email_address, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :phone, 'Contact phone' %>
    <%= form.text_field :phone, id: :ticket_phone, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :ticket_amount,  class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.hidden_field :event_id, id: :ticket_event_id%>
  </div>
  <div class="field">
    <%= form.hidden_field :user_id, id: :ticket_user_id%>
  </div>
  <div class="field">
    <%= form.hidden_field :name, id: :ticket_name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/tickets/_list_tickets.html.erb
<h1>Tickets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Event Date</th>
      <th>Bought by</th>
      <th>Amount </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <% if (current_user.role == 'admin' || ticket.user == current_user) %>
        <tr>
          <td><%= ticket.event.artist %></td>
          <td><%= ticket.event.event_date %></td>
          <td><%= ticket.user.email %></td>
          <td><%= ticket.amount %></td>
          <td><%= link_to 'Show', ticket %></td>
          <% if ticket.event.event_date >= Date.today %>
            <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
            <% if (current_user.role == 'admin' && ticket.to_delete) %>
              <td><%= link_to 'Approve return', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% elsif  (current_user.role == 'admin' && !ticket.to_delete)%>
              <td><%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
            <% if ticket.user == current_user && current_user.role != 'admin' %>
              <td>
                <% if !ticket.to_delete %>
                  <%= link_to 'Return ticket', '/ticket/markForDelete/'+ticket.id.to_s, method: :post, data: { confirm: 'Are you sure?' } %>
                <% else %>
                  Processing return
                <% end %> 
              </td>
            <% end %>
          <% else %>
            <td/><td/>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<%= render 'list_tickets', tickets: @tickets%>

<br>
<%= link_to 'Buy tickets', events_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<h1>Details</h1>
<div class="center">
<p>
  <strong>Event:</strong>
  <%= @ticket.event.artist %>
</p>
<p>
  <strong>Event description:</strong>
  <%= @ticket.event.description %>
</p>
<p>
  <strong>Event date:</strong>
  <%= @ticket.event.event_date %>
</p>
<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @ticket.amount %>
</p>
<p>
  <strong>Contact email address:</strong>
  <%= @ticket.email_address %>
</p>
<p>
  <strong>Contact phone number:</strong>
  <%= @ticket.phone %>
</p>
<% if @ticket.event.event_date >= Date.today %>
  <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>
<%= link_to 'Event', @ticket.event %>
</div>