config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :events, :only => [:index, :new, :create, :show, :edit, :update]

  get '/moremoney', to: 'tickets#more_money'
  post '/ticket/markForDelete/:id', to: 'tickets#set_to_delete'

  get '/tickets/show_filtered/:from/:to', to: 'tickets#filter'

  resources :tickets
  root :to => "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class="container">
  <p class="navbar-text pull-right ">
    <%= link_to 'Home', '/' %> | 
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> | 
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
      %> | 
      <%= link_to "My tickets", tickets_path %> | 
      <%= current_user.money %>$ <%= link_to "More money", '/moremoney'%>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
  </p>

  	<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
</div>
    <%= yield %>
  </body>
</html>